server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        max.block.ms: 3000
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000

  datasource:
    url: jdbc:postgresql://localhost:5433/fraud_db?options=-c%20TimeZone=Asia/Kolkata
    username:  ${DB_USERNAME}
    password:  ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
